using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("LibNoise: A portable, open-source, coherent noise-generating library.")]
[assembly: AssemblyCompanyAttribute("LibNoise Project Contributors")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2011-2012 LibNoise Project Contributors and contributors")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: ComVisibleAttribute(false)]

